modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="battle_of_the_races_by_fzprules"
version="1.0.0"
displayName="Battle Of The Races by FZPrules"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Francisco, MCreator"

[[dependencies.battle_of_the_races_by_fzprules]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




