modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="hard_to_find_biomes_by_fzprules"
version="1.0.0"
displayName="Hard to Find Adventures by FZPrules"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Francisco, MCreator"

[[dependencies.hard_to_find_biomes_by_fzprules]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




